baseURL = "https://openrca.io/"
languageCode = "en-us"
title = "Open RCA"
theme = "docsy"

enableRobotsTXT = true
enableGitInfo = true

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
  blog = "/:section/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

[services]
  [services.googleAnalytics]
    id = "UA-00000000-0"

[languages]
  [languages.en]
    title = "Open RCA"
    description = "Root Cause Analysis for Kubernetes"
    languageName ="English"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "GitHub"
    weight = -99
    url = "https://github.com/openrca"

[params]
  copyright = "Open RCA Authors"
  privacy_policy = "https://policies.google.com/privacy"

  version_menu = "Releases"
  archived_version = false
  version = "0.1"
  url_latest_version = "https://openrca.io"

  github_repo = "https://github.com/openrca.orca"
  github_project_repo = "https://github.com/openrca/orca"

  algolia_docsearch = false
  offlineSearch = true

  [params.ui]
    sidebar_menu_compact = false
    breadcrumb_disable = false
    sidebar_search_disable = true
    navbar_logo = false
    footer_about_disable = false

    [params.ui.feedback]
      enable = false

    [params.ui.readingtime]
      enable = true

  [params.links]
    [[params.links.developer]]
      name = "GitHub"
      url = "https://github.com/openrca/orca"
      icon = "fab fa-github"
      desc = "Development takes place here!"
